name: asgsa_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  cloud_firestore: ^5.6.5
  flutter_animate: ^4.5.0
  pdf: ^3.10.7
  path_provider: ^2.1.2


  google_api_availability: ^5.0.0
  google_sign_in: ^6.3.0


  lottie: ^3.0.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  convex_bottom_bar: ^3.2.0
  animated_bottom_navigation_bar: ^1.3.0
  shimmer_animation: ^2.1.0
  cupertino_icons: ^1.0.6
  printing: ^5.11.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  http: ^1.1.2
  permission_handler: ^11.1.0
  intl: ^0.19.0
  open_file: ^3.3.2
  image_picker: ^1.1.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
