// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwvvLxOhQ1IxTPZZu945imoeaDQSXKjM',
    appId: '1:509949662829:web:579f2b56ee1529dd239164',
    messagingSenderId: '509949662829',
    projectId: 'asgsaapp-a3e83',
    authDomain: 'asgsaapp-a3e83.firebaseapp.com',
    storageBucket: 'asgsaapp-a3e83.firebasestorage.app',
    measurementId: 'G-4GEWXTV26T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuEgCew15NEBGHHwxHB1Y5S_YiqTFbm-I',
    appId: '1:509949662829:ios:a67b5567e393244a239164',
    messagingSenderId: '509949662829',
    projectId: 'asgsaapp-a3e83',
    storageBucket: 'asgsaapp-a3e83.firebasestorage.app',
    iosBundleId: 'com.asgsa.asgsaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuEgCew15NEBGHHwxHB1Y5S_YiqTFbm-I',
    appId: '1:509949662829:ios:a67b5567e393244a239164',
    messagingSenderId: '509949662829',
    projectId: 'asgsaapp-a3e83',
    storageBucket: 'asgsaapp-a3e83.firebasestorage.app',
    iosBundleId: 'com.asgsa.asgsaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNwvvLxOhQ1IxTPZZu945imoeaDQSXKjM',
    appId: '1:509949662829:web:f223ceaf4ef63a24239164',
    messagingSenderId: '509949662829',
    projectId: 'asgsaapp-a3e83',
    authDomain: 'asgsaapp-a3e83.firebaseapp.com',
    storageBucket: 'asgsaapp-a3e83.firebasestorage.app',
    measurementId: 'G-HKL60L98XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gk6x0K8Np2wawow3C1aa3ZpSUhOoGp8',
    appId: '1:509949662829:android:e1343642d79be0e3239164',
    messagingSenderId: '509949662829',
    projectId: 'asgsaapp-a3e83',
    storageBucket: 'asgsaapp-a3e83.firebasestorage.app',
  );

}